name: ar_face
channels:
  - pytorch # Important for GPU-enabled PyTorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.10 # Specify Python version
  - ffmpeg # Install ffmpeg executable via conda
  - pip
  - pip:
      - torch # Let pip resolve the best CUDA-compatible version
      - torchvision
      - torchaudio
      - transformers
      - "ffmpeg-python" # Python wrapper for ffmpeg
      - sounddevice
      - numpy
      - wavio
      - google-generativeai
